services:

  valkey:
    image: valkey/valkey
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    # volumes:
    #   - 'data:./vk'
  
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game
    ports:
      - '5432:5432'
    volumes:
      - ./pg:/data/postgres

volumes:
  valkey_data:
    driver: local